### ISSUE TITLE
ValueError: numpy.ndarray size changed, may indicate binary incompatibility.

### ISSUE THREAD

**Issue by maciejbiesek** [ddangelov/Top2Vec#236] opened 2022-01-07 10:08 UTC
A few days ago the problem with `ValueError: numpy.ndarray size changed, may indicate binary incompatibility.` occurred during executing the code that worked one week ago without any problems.

The same issue is with BERTopic (https://github.com/MaartenGr/BERTopic/issues/392), so I thought maybe it would be beneficial to link it there. For now, it seems there is no easy solution to that problem

**Comment by ddangelov** [comment] 2022-04-03 22:36
What `embedding_model` did you use and during which step did you get this error?

**Comment by Uzay-G** [comment] 2022-05-03 10:02
I get this also with universal sentence decoder when I import top2vec. I think it's because on python 3.10, numba requires numpy <=1.21 but gensim requires numba >=1.22 (https://github.com/RaRe-Technologies/gensim/blob/93ed2fbe27dab41b459bd09bd5b19ed5d7e01908/.github/workflows/build-wheels.yml#L95).

So the library is not usable for python3.10

**Comment by ddangelov** [comment] 2022-05-04 18:01
I have no issues with this and I have python 3.8.5 so I don't think that is the issue.

**Comment by Uzay-G** [comment] 2022-05-04 18:02
The problem is with python 3.10

**Comment by ddangelov** [comment] 2022-05-04 18:04
setup.py specifies `python_requires='>=3.6'`

**Comment by Uzay-G** [comment] 2022-05-04 18:07
3.10 is >= 3.6?

I don't mean 3.1, python 3.10 (https://www.python.org/downloads/release/python-3100/) was released in october.

**Comment by Uzay-G** [comment] 2022-05-04 18:07
It's not an old release.

**Comment by ddangelov** [comment] 2022-05-04 18:10
Ok got it. Will investigate.

**Closed** 2022-11-13 21:59 UTC
